config/routes.rb
Rails.application.routes.draw do
 
    root "home#index"
    resources :home
	#root "users#new"
	resources :users do
		member do
			get :confirm_email
		end
	end
	resources :sessions
	resources :posts
 #get "/users/new" => "users#new"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader:attachment,AttachmentUploader
	validates :name, presence: true
	
	
end

app/models/user.rb
class User < ApplicationRecord
  before_create :confirmation_token
  has_secure_password
  validates :name,:password, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }


   def confirmation_token
   	if self.confirm_token.blank?
   		self.confirm_token = SecureRandom.urlsafe_base64.to_s

   	end
   end

   def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def user
  	User.find(session[:user_id]) if session[:user_id]
  end

  def login
  	 unless session[:user_id]
  	 	flash[:errors] = ["you must login first"]
  	 	redirect_to new_user_path
  	 end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :login
	def index
		@post = Post.all
	end

	def new
		@posts=Post.new
		
	end

	def create
       post=Post.new(post_params)
		if post.save

			redirect_to posts_path
		else
			flash[:errors]=post.errors.full_messages
			redirect_to new_post_path
		end
end

 def destroy
  	dpost=Post.find(params[:id])
  	dpost.destroy
  	redirect_to posts_path
  end 

	private
	def post_params
		params.require(:post).permit(:name,:attachment)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

         def create
		user=User.find_by(email: params[:email])
		  if user && user.authenticate(params[:password])
			   if user.email_confirmed
			   session[:user_id] = user.id
			   redirect_to "/users/<%= user.id %>"
		else
			   flash[:errors]=["Please activate your account"]
			   redirect_to new_user_path
	       end
		else
			flash[:errors]=["Invalid combination"]
			redirect_to new_user_path
		end
	end





	def destroy
		reset session
		redirect_to new_user_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#before_action :login
  def index
  	@users=User.all
  end

  def new
  	@user=User.new
  end

def create
  	user=User.new(user_params)
  	if user.save
      UserMailer.registration_confirmation(user).deliver
      flash[:success] = "Registraion completed! Please Confirm your Email address."
  		session[:user_id] = user.id
  		redirect_to users_path
  	else
  		flash[:errors] = user.errors.full_messages
  		redirect_to new_user_path

  	end
  end

   def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user_params
      user.email_activate
      flash[:success] = "Welcome to St.Anne's School! Your account has been confirmed."
      redirect_to root_url
    end
   end

   def show
    @user = user
   end

  	 private 
	def user_params
		params.require(:user).permit(:name, :email,:password,:password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		 "https://gravatar.com/avatar/#{gravatar_id}.jpg"
		end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	
end

app/views/home/index.html.erb
 <% provide(:title ,"Home Page") %>
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">St.Anne's</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/home">Home</a></li>
        <li><a href="#">Developers</a></li>
        <li><a href="#">Contacts</a></li> 
        <li><a href="/users">Users</a></li> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/users/new"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

<br>


<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
       <%= image_tag("pictures/school.jpg", width: '1200px',height: '400px') %>
      
        <div class="carousel-caption">
          
        </div>      
      </div>

      <div class="item">
       <%= image_tag("pictures/friends.jpg", width: '1200px',height: '400px') %>
    
        <div class="carousel-caption">
         
        </div>      
      </div>
    </div>








    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
  
<div class="container text-center">    
  <h3></h3><br>
  <div class="row">
    <div class="col-sm-4">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS4WBDiyT1pms2grmJyFZGMbMilTzytV78hSKvl5lGEQHBq8Ep" class="img-responsive" style="width:100%" alt="Image">
      <p>KinderGarden</p>
    </div>
    <div class="col-sm-4"> 
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnAnDSZWy7PLaTAV5AEXtPrxJ8pjl5xzCcTSz7Wmn_swbONnHJ" class="img-responsive" style="width:100%" alt="Image">
      <p>School</p>    
    </div>
    <div class="col-sm-4">
      <div class="well">
       <p>Work in progress</p>
      </div>
      <div class="well">
       <p>Work in progress</p>
      </div>
    </div>
  </div>
</div><br>



<div class="container-fluid bg-3 text-center">    
  <h3>Developers</h3><br>
  <div class="row">
    <div class="col-sm-4">
      <h4><a href="mailto:#">Vamsi Krishna</a></h4>
      <p>Front-End Web Developer</p>
     <%= image_tag("pictures/vamsi.jpg", width: '250px',height: '300px') %>
    </div>
    <div class="col-sm-4"> 
      <h4><a href="mailto:madhuvadde2709@gmail.com">Madhu Vadde</a></h4>
      <p>Full Stack Web Developer</p>
       <%= image_tag("pictures/madhu.jpg", width: '250px',height: '300px') %>
    </div>
    <div class="col-sm-4"> 
     <h4><a href="mailto:#">Sai Chaitanya Reddy</a></h4>
      <p>Front-End Web Developer</p>
      <%= image_tag("pictures/chaitu.jpg", width: '250px',height: '300px') %>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p></p>
</footer>



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>

    <div class="container">
    <%= yield %>
    </div>
   
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/index.html.erb
<% provide(:title ,"Posts") %>
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="/users/:id">Profile</a>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        
         
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>


<nav class="navbar navbar-default">

<table class="table">
	<thead>
		<tr>
			<th>Material name</th>
			<th>Download link</th>
			<th>Action</th>
		</tr>
	</thead>
			<tbody>
			<% @post.each do |p| %>
			<tr>
			<td><%= p.name %></td>
			<td><%= link_to 'Download', p.attachment_url %></td>
			<td><%= link_to 'Delete', p, method: :delete, confirm: "Are you sure to delete #{p.name}?" %></td>
			</tr>
			</tbody>
			<% end %>
		</tbody>
		

		<br>
		
	</table>
	</nav>
<center>	<h4><%= link_to "New Post",new_post_path %> </h4> </center>

app/views/posts/new.html.erb
<% provide(:title ,"Upload files") %>
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">St.Anne's</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
       <a class="navbar-brand" href="/users/:id">Profile</a>
        <li><a href="/posts"><b>posts</b></a></li> 
         
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>




<center>

<% if flash[:errors] %>
<p> <% flash[:errors].each do |err| %></p>
<div class="row">
<p class="text-danger"> <%= err %> </p>
<% end %>
<% end %>



<%= form_for @posts do |f| %>
<%= f.label :Filename %>
<%= f.text_field :name %>
<br> 
<%= f.label :file %>
<%= f.file_field :attachment %>
<br>
<%= f.submit "Save" %>
<% end %>
</center>

app/views/users/index.html.erb
<% provide(:title ,"Users page") %>

<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">St.Anne's</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/home">Home</a></li>
        <li><a href="/developers/index">Developers</a></li>
        <li><a href="#">Contacts</a></li> 
        <li><a href="/users">Users</a></li> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/users/new"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>
<br>
<br>
<br>
<br>


<center>
<h1>There are about <%= @users.count %> users</h1>
<div class="container">
<table class="table">

	<thead>
	<tr>
		<td>Name</td>
        <td>Email</td>
       <!-- <td>Show</td> -->
        </tr>
	</thead>

	<tbody>
		<% @users.each do |u| %>
		<tr>
		<td><%= u.name %></td>
		<td><%= u.email %></td>
	<!--	<td><a href="/users/<%= u.id %>">Profile</td> -->
		</tr>
		<% end %>
		</div>
		
	</tbody>
</table>
</div>
</center>
</body>
</html>

app/views/users/new.html.erb
<% provide(:title, "register and login") %>

<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">St.Anne's</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/home">Home</a></li>
        <li><a href="/developers/index">Developers</a></li>
        <li><a href="#">Contacts</a></li> 
        <li><a href="/users">Users</a></li> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/users/new"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>
<br>
<br>
<br>
<br>
<% if flash[:errors] %>
<div class="row">
<% flash[:errors].each do |e| %>
<p class="text-danger">
<%= e %> 
</p>
<% end %>
</div>
<% end %>

<%= flash[:success] %>


<div class="row">
<div id="registration" class="col-md-6">
<div id="box">
<h1 id="register"> Register </h1>

<%= form_for @user do |f| %>
<div class="form-group">
 <%= f.label :name %>
 <%= f.text_field :name %>
 </div>

 <div class="form-group">
  <%= f.label :email %>
 <%= f.email_field :email %>
 </div>

<div class="form-group">
  <%= f.label :password %>
 <%= f.password_field :password %>
 </div>

 <div class="form-group">
  <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation %>
 </div>

 <div class="form-group">
 <div id="submit">
 <%= f.submit :signup %>
 </div>
 </div>

  <% end %>
  </div>
</div>

  
  <div id="login" class="col-md-6">
  <h1 id="heading">login </h1>

  <%= form_tag sessions_path do %>
<div class="form-group">
 <%=label_tag :email %>
 <%= email_field_tag :email %>
 </div>

 <div class="form-group">
  <%= label_tag :password %>
 <%= password_field_tag :password %>
 </div>

 <div class="form-group">
 <div id="submit">
 <%= submit_tag "login" %>
 </div>
 </div>
 
  
 <% end %>

 </div>



  

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<nav class="navbar  navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">Profile</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="/posts"><b>posts</b></a></li> 
         
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-4 sidenav">
      <%= image_tag avatar_url(@user) %>
      <h3><b><%=  @user.name %></b></h3>
      <!--<h3><%= @user.created_at %></h3>
      <h3><%= @user.updated_at %></h3>-->
    </div>
    <div class="col-sm-8 text-left"> 
      <h1>Welcome</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <hr>
      <h3>Test</h3>
      <p>Lorem ipsum...</p>
    </div>
<footer class="container-fluid text-center">
<div class="col-sm-12 text-left"> 
  <p>Footer Text Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</footer>